CONTRIBUTING.md
README.md

Contribution guideline contains some information that is supposed to help get started with the project. 
Tried to write down everything that was discussed and decided so far. 
Let me know if I missed anything!

Contribution guideline

---

Say Their Names.xcodeproj/project.pbxproj.orig
Say Their Names.xcodeproj/xcshareddata/xcschemes/Say Their Names.xcscheme
Say Their Names/Source/Controller/Home/HomeController.swift
Say Their Names/Source/Controller/Home/Person/PersonController.swift
Say Their NamesTests/Say_Their_NamesTests.swift
SayTheirNamesUITests/Info.plist
SayTheirNamesUITests/SayTheirNamesUITests.swift
SayTheirNamesUITests/XCUIApplication+SayTheirName.swift

This is a restart of the PR https://github.com/Say-Their-Name/ios/pull/18
Main things added here are 
- test validating collections views
- test validation tab bar
- test validating person tap action

Create initial UI tests for Home screen

---

Say Their Names/Source/View/Home/Person/PersonCell.xib

Outlet name was changed and it lead to the crash on start, solved it with reconnecting the outlets

Changed outlet name lead to crash, reconnected outlet

---

Say Their Names/Source/Controller/Home/CollectionViewDataSource/LocationCollectionViewDataSource.swift
Say Their Names/Source/Controller/Home/CollectionViewDataSource/PersonCollectionViewDataSource.swift
Say Their Names/Source/Controller/Home/HomeController.swift
Say Their Names/Source/Controller/Home/HomeView.swift

Accidentally left couple things commented out during merge of #28. Fixing that now + the tag approach was confusing to me, so improved that too.

Post-merge cleanup

---

SayTheirNames.xcodeproj/project.pbxproj

Noticed these weren't referenced. This way it's easier to see them.

Add readme and contributing to the Xcode project

---

SayTheirNames.xcodeproj/project.pbxproj
SayTheirNames/Source/Controller/Home/HomeView.swift
SayTheirNames/Source/Utils/Extentions/UIButton++.swift
SayTheirNames/Source/View/Home/Person/PersonCell.swift

Add button extension with image initializer
[Here](https://trello.com/c/JcmifVID/48-refactor-buttons-with-images-to-use-a-new-uiimagebutton-object)

Add Button Extension With Image Initializer

---

CONTRIBUTING.md

Added basic FAQ to recently asked questions.

Update CONTRIBUTING.md with FAQ

---

SayTheirNames/Source/Model/Donation.swift
SayTheirNames/Source/Model/Image.swift
SayTheirNames/Source/Model/Link.swift
SayTheirNames/Source/Model/Location.swift
SayTheirNames/Source/Model/Media.swift
SayTheirNames/Source/Model/Person.swift
SayTheirNames/Source/Model/Petition.swift
SayTheirNames/Source/Model/SocialMedia.swift

Changed our model to be nonmutable. 
Once we get things ready for donations, a few will become mutable.

changed to non-mutable

---

SayTheirNames.xcodeproj/project.pbxproj
SayTheirNames/Source/Model/Donation.swift
SayTheirNames/Source/Model/Location.swift
SayTheirNames/Source/Model/Person.swift
SayTheirNames/Source/Model/Petition.swift
SayTheirNames/Source/Model/Search.swift
SayTheirNames/Source/Model/SocialMedia.swift
SayTheirNames/Source/Service/Networking/NetworkRequestor.swift
SayTheirNames/Source/Service/Networking/Requestors/DonationsNetworkRequestor.swift
SayTheirNames/Source/Service/Networking/Requestors/PeopleNetworkRequestor.swift
SayTheirNames/Source/Service/Networking/Requestors/PetitionsNetworkRequestor.swift
SayTheirNames/Source/Service/Networking/Requestors/SearchNetworkRequestor.swift
SayTheirNames/Source/Service/Service.swift
SayTheirNames/Source/Utils/Extentions/URLComponents+STN.swift
SayTheirNamesTests/ServiceTests/NetworkRequestorTests.swift
SayTheirNamesTests/ServiceTests/Requestors/DonationsNetworkRequestorTests.swift
SayTheirNamesTests/ServiceTests/Requestors/PeopleNetworkRequestorTests.swift
SayTheirNamesTests/ServiceTests/Requestors/PetitionsNetworkRequestorTests.swift

- Full search
- Person search (name, city, country)
- Petition search (name, type)
- Donation search (name, type)

Added more network requestors

---

SayTheirNames/Source/Controller/Home/CollectionViewDataSource/LocationCollectionViewDataSource.swift
SayTheirNames/Source/Controller/Home/CollectionViewDataSource/PersonCollectionViewDataSource.swift
SayTheirNames/Source/Controller/Home/HomeController.swift
SayTheirNames/Source/Controller/Home/Person/PersonController.xib
SayTheirNames/Source/View/Home/Person/PersonCell.swift
SayTheirNames/Source/View/Home/Person/PersonHeaderCell.xib
SayTheirNames/Source/View/Home/Person/PersonPhotoCell.swift
SayTheirNames/Source/View/Home/Search/SearchResultCell.xib

What this PR do?
I added accessibility labels and enabled voice-over feature for all of the UIs. 
Some of the accessibility labels have to be spelled phonetically so VO can read it correctly. 
How to test? 
On a device: enable voice over and open the app. Try to go through each UI. (try not to get lost)
On a simulator: open accessibility inspector and enable voice over. It will automatically go through the UIs and read them out.

Add voice over support

---

SayTheirNames/Source/Controller/Petitions/PetitionDetailView.swift
SayTheirNames/Source/Controller/Petitions/PetitionTableViewCell.swift
SayTheirNames/Source/View/Home/Person/PersonCell.swift
SayTheirNames/Source/View/Home/Person/PersonPhotoCell.swift

Added support for smart invert to photos and large image views created in code.
I haven't added this to image views in storyboards as I understand these are being removed, but I can add later if needed.
This is a visual change when smart invert is enabled, but unfortunately ca't be represented I screenshots.

Support for smart invert

---

SayTheirNames/Resources/Base.lproj/Localizable.strings
SayTheirNames/Resources/Generated/strings.swift
SayTheirNames/Source/Controller/Home/Person/PersonController.swift
SayTheirNames/Source/Controller/Home/Person/Views/PersonHashtagTableViewCell.swift
SayTheirNames/Source/Controller/Home/Person/Views/PersonInfoTableViewCell.swift
SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsTableViewCell.swift
SayTheirNames/Source/Controller/Home/Person/Views/PersonOverviewTableViewCell.swift

* Adds localization to `PersonController` and views it uses.
* Fixes some indentation in `PersonController` that xcode didn't like.
Also added some Trello cards to To Do that capture updating the other language localization files.

[CHORE] Adds localization to PersonController.

---

SayTheirNames/Source/Components/CustomNavigationBar.swift
SayTheirNames/Source/Components/CustomSearchBar.swift
SayTheirNames/Source/Components/MainTabBarController.swift
SayTheirNames/Source/Controller/Home/HomeController.swift
SayTheirNames/Source/Controller/Home/HomeView.swift
SayTheirNames/Source/Controller/Home/Person/PersonController.swift
SayTheirNames/Source/Controller/Home/Person/Views/PersonHashtagTableViewCell.swift
SayTheirNames/Source/Controller/Home/Person/Views/PersonInfoTableViewCell.swift
SayTheirNames/Source/Controller/Home/Person/Views/PersonMediaCollectionViewCell.swift
SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsCollectionViewCell.swift
SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsTableViewCell.swift
SayTheirNames/Source/Controller/Home/Person/Views/PersonOverviewTableViewCell.swift
SayTheirNames/Source/Controller/Home/Person/Views/PersonPhotoTableViewCell.swift
SayTheirNames/Source/Controller/Petitions/PetitionDetailView.swift
SayTheirNames/Source/Utils/Color/UIColor+Resource.swift
SayTheirNames/Source/View/ButtonContainerView.swift
SayTheirNames/Source/View/Common/STNNavigationBar.swift
SayTheirNames/Source/View/ImageWithBlurView.swift

https://trello.com/c/Yu3S76nY/68-collect-all-the-colors-set-through-uicolor-to-use-uicolorresource-extension
Start of Semantic coloring. Open to feedback as I'm sure we can improve color naming.

[CHORE] Use UIColor.STN extension

---

SayTheirNames/Source/View/Filter/FilterCategoryCell.swift

Follow up refactor to use constraint convenience method from suggestion on https://github.com/Say-Their-Name/say-their-names-ios/pull/107

[Chore] Refactor filter category cell constraints

---

SayTheirNames/Source/View/CallToAction/CallToActionCell.swift
SayTheirNames/Source/View/CallToAction/CallToActionCollectionView.swift

Bugfix - the collection view cell broke text constraints while scrolling, which can lead to performance degradation and unexpected layout behavior. I updated several of the constraints and adjusted the cell height to match designs + fix the issue.

[BUG] - Fix auto-layout breaks & minor design detail

---

SayTheirNames.xcodeproj/project.pbxproj
SayTheirNames/Source/Controller/Home/HomeView.swift
SayTheirNames/Source/FeatureFlags.swift
SayTheirNames/Source/View/Home/Person/PersonCell.swift

This PR introduces a FeatureFlags to be used to enable/disable features within the app. Additionally it uses the FeatureFlags.boomarksEnabled in two places to hide the button to bookmark a person.

[FEATURE] Hide bookmarks for v1 launch

---

SayTheirNames.xcodeproj/project.pbxproj
SayTheirNames/Resources/Base.lproj/Localizable.strings
SayTheirNames/Resources/Generated/strings.swift
SayTheirNames/Resources/ko.lproj/Localizable.strings

Adding Korean strings. I studied Korean for ~6 years. I also had a close Korean friend double check my work. I will gladly maintain this list and add as necessary!
Also, found and fixed a little typo in the word `verified` in the base file.

[FEAT] Add Korean localization

---

SayTheirNames/Source/Components/CustomSearchBar.swift
SayTheirNames/Source/Components/MainTabBarController.swift
SayTheirNames/Source/Controller/Donations/DonationsController.swift
SayTheirNames/Source/Controller/Donations/DonationsView.swift
SayTheirNames/Source/Controller/Home/HomeController.swift
SayTheirNames/Source/Controller/Home/HomeView.swift
SayTheirNames/Source/Controller/Petitions/PetitionsController.swift
SayTheirNames/Source/Controller/Petitions/PetitionsView.swift

Remove custom navigation views and convert them to native

---

SayTheirNames/Source/Controller/Home/Person/PersonController.swift
SayTheirNames/Source/Dependency/Networking/Requestors/PeopleNetworkRequestor.swift
SayTheirNames/Source/Model/Person.swift
SayTheirNamesTests/DataSourceTests/PersonCollectionViewDataSourceHelperTests.swift

- Add API call to fetch a person's detailed information that's required for the Person Details screen.
- Stub methods to reconfigure the Person Details screen.

[CHORE] - Add Person Details Networking

---

SayTheirNames/Source/Controller/Donations/DonationsController.swift
SayTheirNames/Source/View/CallToAction/CallToAction.swift
SayTheirNames/Source/View/CallToAction/CallToActionCell.swift

This is PR adds functionality to handle "find out more" button action, which reveals donations more details view controller.
Currently it was add in cell selection and added ad Todo to remove from there.
PR presumes "id" property as unique property for Donation model.

[FEAT]: donations cell find-out-more button action added

---

SayTheirNames.xcodeproj/project.pbxproj
SayTheirNames/Source/Components/MainTabBarController.swift
SayTheirNames/Source/Controller/Donations/DonationsController.swift
SayTheirNames/Source/Controller/Home/HomeController.swift
SayTheirNames/Source/Controller/Petitions/PetitionsController.swift
SayTheirNames/Source/Dependency/Deep Linking/Deep Links/AboutDeepLink.swift
SayTheirNames/Source/Dependency/Deep Linking/Deep Links/DonationsDeepLink.swift
SayTheirNames/Source/Dependency/Deep Linking/Deep Links/HomeDeepLink.swift
SayTheirNames/Source/Dependency/Deep Linking/Deep Links/PersonDeepLink.swift
SayTheirNames/Source/Dependency/Deep Linking/Deep Links/PetitionsDeepLink.swift
SayTheirNames/Source/Dependency/Deep Linking/DeepLink.swift
SayTheirNames/Source/Dependency/Deep Linking/DeepLinkDetails.swift
SayTheirNames/Source/Dependency/Deep Linking/DeepLinkHandler.swift
SayTheirNames/Source/Dependency/Deep Linking/DeepLinkSupport.swift
SayTheirNames/Source/Dependency/Navigator/Navigator.swift

Some minor updates from a PR after it was closed #149

[CHORE] Deep linking upates

---

SayTheirNames/Resources/Base.lproj/Localizable.strings
SayTheirNames/Resources/Generated/strings.swift
SayTheirNames/Source/Components/MainTabBarController.swift
SayTheirNames/Source/Controller/Donations/DonationsController.swift
SayTheirNames/Source/Controller/More/MoreController.swift
SayTheirNames/Source/Controller/Petitions/PetitionsController.swift

Capitalize all titles of screens
Rename More tab to About according to design. All other localizations are already on "about"

[UI] Text tweaks

---

SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController.swift

[FIX] STN logo appears over text in donation details (dark mode only)

---

SayTheirNames/Resources/Base.lproj/Localizable.strings
SayTheirNames/Resources/Generated/strings.swift
SayTheirNames/Resources/ar.lproj/Localizable.strings
SayTheirNames/Resources/fr.lproj/Localizable.strings
SayTheirNames/Resources/ko.lproj/Localizable.strings
SayTheirNames/Resources/pt-BR.lproj/Localizable.strings
SayTheirNames/Resources/ru-RU.lproj/Localizable.strings

- ran SwiftGen again to generate a clean L10n strings file
- replace all instances of `Strings.` with `L10n.`
- removed the TypeAlias file and Typealiases folder.

[CHORE] Rename all instances of `Strings` to `L10n`

---

SayTheirNames/Source/Controller/Donations/DonationsController.swift
SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DMDCollectionViewDataSource.swift
SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController.swift
SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDTitleCell.swift
SayTheirNames/Source/Controller/Home/Person/PersonController.swift
SayTheirNames/Source/Controller/Petitions/PetitionsController.swift
SayTheirNames/Source/Model/Donation.swift
SayTheirNames/Source/Model/Petition.swift

Implementing the petition screen.
This is a DRAFT PR for some early feedback. Still will need to rename lots of things, add some localizations and make UI fixes so the screen looks nicer when not much data is present. 
The functionality should be all in place though.
TODO:
TODO as-separate-tasks:

[FEAT] Petition details (reusing donation details)

---

SayTheirNames/Source/View/ButtonContainerView.swift

[UI] Make CTA button wider for Donation details screen

---

SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDTextContentCell.swift
SayTheirNames/Source/Controller/Home/CollectionViewDataSource/Carousel/CarouselCollectionViewCell.swift
SayTheirNames/Source/Controller/Home/Person/Views/PersonMediaCollectionViewCell.swift
SayTheirNames/Source/View/Hashtag/HashtagViewCollectionViewCell.swift
SayTheirNames/Source/View/Home/Person/PersonCell.swift

- Fixes an issue where incorrect information could be displayed on a recycled cell.

[BUG] - Fix issue where cells would display the wrong information

---

SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController.swift
SayTheirNames/Source/Controller/Home/Person/PersonController.swift
SayTheirNames/Source/Dependency/ShareService.swift

This PR creates an URL from a Shareable so the ActivitySheet shows better options for the user.
Also changes the signature of the function, so call sites are updated too.
| Before | After |
|:------:|:-----:|

[UI] Pass URL from Sharable to UIActivityVC to improve UX

---

SayTheirNames/Resources/Base.lproj/Localizable.strings
SayTheirNames/Resources/Generated/strings.swift
SayTheirNames/Resources/ar.lproj/Localizable.strings
SayTheirNames/Resources/en.lproj/Localizable.strings
SayTheirNames/Resources/fr.lproj/Localizable.strings
SayTheirNames/Resources/ko.lproj/Localizable.strings
SayTheirNames/Resources/nl.lproj/Localizable.strings
SayTheirNames/Resources/pt-BR.lproj/Localizable.strings
SayTheirNames/Resources/ru.lproj/Localizable.strings

Added missing translation.
Note : a few of the comments had been modified in the localise.biz so they got updated in all the translation files (that's why they all have changes, including strings.swift.

[CHORE] L10n update for FR

---

SayTheirNames/Source/FeatureFlags.swift

Enable images again (placeholder for now, will require backend update for new ones)

[UI] Enable images on donations and petitions

---

SayTheirNames/Resources/Color.xcassets/background.colorset/Contents.json
SayTheirNames/Source/Controller/Donations/DonationsView.swift
SayTheirNames/Source/Controller/Home/HomeController.swift
SayTheirNames/Source/Controller/Home/HomeView.swift
SayTheirNames/Source/Controller/Launch/LaunchScreen.swift
SayTheirNames/Source/Controller/Petitions/PetitionsView.swift
SayTheirNames/Source/View/CallToAction/CallToActionCollectionView.swift
SayTheirNames/Source/View/CallToAction/TagView.swift
SayTheirNames/Source/View/Common/STNNavigationBar.swift
SayTheirNames/Source/View/Filter/FiltersCollectionView.swift

[UI] BackgroundColor to resolve to SystemBackground, update usages for consistency.

---

SayTheirNames/Source/View/Home/Person/PersonCell.swift

Fixes #228.
I just changed the `profileImageView` constraints.

[FIX] Fix PersonCell image contraints
